workspace(
    name = "PSI-CA",
)

load("@PSI-CA//:preload.bzl", "psi_preload")

psi_preload()

load("@PSI-CA//:deps.bzl", "psi_deps")

psi_deps()


# Finish python setup
load("@pip_deps//:requirements.bzl", "install_deps")

install_deps()



